<a href="https://colab.research.google.com/github/ousabu/aiousama/blob/master/naive_bayes_2_email_spam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd


In [2]:
df=pd.read_csv('spam2.csv')

In [3]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df.groupby('Category').describe()

Message                                                               
           count unique                                                top freq
Category                                                                       
ham         4825   4516                             Sorry, I'll call later   30
spam         747    641  Please call our customer service representativ...    4

In [11]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [20]:
def filt(x):
  temp=0
  if x=='spam':
     temp=1
  else: 
     temp=0 
  return temp    

In [23]:
df['spam']=df.Category.apply(lambda x: 1 if x=='spam' else 0)

In [24]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [49]:
df0=df[df.spam==0]
df1=df[df.spam==1]

In [50]:
df0=df0.sample(len(df1))
df_new=df0.append(df1)

In [51]:
x=df_new.Message
y=df_new.spam

In [58]:
df_new.spam.value_counts()

1    747
0    747
Name: spam, dtype: int64

In [59]:
df.spam.value_counts()

0    4825
1     747
Name: spam, dtype: int64

In [60]:
from sklearn.model_selection import train_test_split


In [61]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=200,stratify=y)

In [62]:
x[:10]

2244    Boo I'm on my way to my moms. She's making tor...
2151        The table's occupied, I'm waiting by the tree
129     HEY GIRL. HOW R U? HOPE U R WELL ME AN DEL R B...
1849    I dont want to hear philosophy. Just say what ...
858     Hai ana tomarrow am coming on morning.  &lt;DE...
4165                  Its ok, called mom instead have fun
3929       Babe ? I lost you ... Will you try rebooting ?
1467    Your account has been refilled successfully by...
5529                            What about this one then.
4392    The greatest test of courage on earth is to be...
Name: Message, dtype: object

In [63]:
x_train.values.shape

(1195,)

In [64]:
from sklearn.feature_extraction.text import CountVectorizer

In [65]:
vec=CountVectorizer()
x_train_vec=vec.fit_transform(x_train.values)
x_train_vec.toarray()[:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [66]:
from sklearn.naive_bayes import MultinomialNB

In [67]:
model2=MultinomialNB()
model2.fit(x_train_vec,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [68]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]
email_vec=vec.transform(emails)
model2.predict(email_vec)

array([0, 1])

In [69]:
x_test_vec=vec.transform(x_test)
model2.predict(x_test_vec)

array([1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0])

In [70]:
model2.score(x_test_vec,y_test)

0.9331103678929766

spam의 데이터 벨런스를 맞추었을때 정확도가 떨어짐
조정전 98.7% 조정후 93.33%

In [71]:

from sklearn.pipeline import Pipeline
clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [72]:
clf.fit(x_train,y_train)

Pipeline(memory=None,
         steps=[('vectorizer',
                 CountVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words=None, strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, vocabulary=None)),
                ('nb',
                 MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))],
         verbose=False)

In [74]:
clf.score(x_test,y_test)

0.9331103678929766

In [75]:
clf.predict(emails)

array([0, 1])