<a href="https://colab.research.google.com/github/ousabu/aiousama/blob/master/Naive_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np


In [2]:
df=pd.read_csv('titanic.csv')

In [3]:
df.head()

PassengerId  ... Survived
0            1  ...        0
1            2  ...        1
2            3  ...        1
3            4  ...        1
4            5  ...        0

[5 rows x 12 columns]

In [4]:
df.shape

(891, 12)

In [6]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis=1,inplace=True)

In [7]:
df.head()

Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [29]:
df.groupby('Sex').mean()['Survived']

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

In [30]:
df.Survived.value_counts()

0    549
1    342
Name: Survived, dtype: int64

In [31]:
df0=df[df.Survived==0]
df1=df[df.Survived==1]

In [32]:
df0=df0.sample(342)

In [34]:
df=df0.append(df1)

In [35]:
df.shape

(684, 5)

In [36]:
x=df.drop('Survived',axis=1)
y=df.Survived

In [37]:
dummies=pd.get_dummies(x.Sex)

In [38]:
dummies

female  male
686       0     1
42        0     1
671       0     1
478       0     1
574       0     1
..      ...   ...
875       1     0
879       1     0
880       1     0
887       1     0
889       0     1

[684 rows x 2 columns]

In [39]:
x=pd.concat([x,dummies],axis=1)

In [40]:
x.head()

Pclass   Sex   Age     Fare  female  male
686       3  male  14.0  39.6875       0     1
42        3  male   NaN   7.8958       0     1
671       1  male  31.0  52.0000       0     1
478       3  male  22.0   7.5208       0     1
574       3  male  16.0   8.0500       0     1

In [41]:
x.drop(['Sex','male'],inplace=True,axis=1)

In [42]:
x.head()

Pclass   Age     Fare  female
686       3  14.0  39.6875       0
42        3   NaN   7.8958       0
671       1  31.0  52.0000       0
478       3  22.0   7.5208       0
574       3  16.0   8.0500       0

In [43]:
x.isnull().sum()

Pclass      0
Age       134
Fare        0
female      0
dtype: int64

In [44]:
x.Age.fillna(x.Age.mean(),inplace=True)

In [45]:
x.head()

Pclass        Age     Fare  female
686       3  14.000000  39.6875       0
42        3  29.533945   7.8958       0
671       1  31.000000  52.0000       0
478       3  22.000000   7.5208       0
574       3  16.000000   8.0500       0

In [46]:
x.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 684 entries, 686 to 889
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Pclass  684 non-null    int64  
 1   Age     684 non-null    float64
 2   Fare    684 non-null    float64
 3   female  684 non-null    uint8  
dtypes: float64(2), int64(1), uint8(1)
memory usage: 22.0 KB


In [55]:
from sklearn.model_selection import train_test_split

In [56]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,stratify=y,random_state=200)

In [57]:
from sklearn.naive_bayes import GaussianNB

In [58]:
model=GaussianNB()


In [59]:
model.fit(x_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [60]:
model.score(x_test,y_test)

0.7299270072992701

In [61]:
x_test[:10]

Pclass        Age      Fare  female
885       3  39.000000   29.1250       1
649       3  23.000000    7.5500       1
42        3  29.533945    7.8958       0
82        3  29.533945    7.7875       1
820       1  52.000000   93.5000       1
214       3  29.533945    7.7500       0
543       2  32.000000   26.0000       0
164       3   1.000000   39.6875       0
22        3  15.000000    8.0292       1
373       1  22.000000  135.6333       0

In [67]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

In [86]:
model2=LogisticRegression(C=10,max_iter=100)

In [87]:
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.fit_transform(x_test)

In [88]:
model2.fit(x_train,y_train)

LogisticRegression(C=10, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [89]:
model2.score(x_test,y_test)

0.7664233576642335

In [90]:
from sklearn.model_selection import cross_val_score

In [96]:
result=cross_val_score(model,x_train,y_train,cv=5)

In [97]:
np.mean(result)

0.7623019182652211

In [95]:
resu2=cross_val_score(model2,x_train,y_train,cv=5)
np.mean(resu2)

0.7787489574645537

In [99]:
model.predict_proba(x_test)[:5]

array([[9.38352990e-03, 9.90616470e-01],
       [8.80903082e-03, 9.91190969e-01],
       [5.55785073e-01, 4.44214927e-01],
       [9.02811155e-03, 9.90971888e-01],
       [5.71861772e-05, 9.99942814e-01]])

In [102]:
model.predict(x_test)[:10]

array([1, 1, 0, 1, 1, 0, 1, 0, 1, 1])

In [103]:
model2.predict(x_test)[:10]

array([1, 1, 0, 1, 1, 0, 0, 0, 1, 1])