<a href="https://colab.research.google.com/github/ousabu/aiousama/blob/master/tweet_convidipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras import Sequential
from tensorflow.keras.layers import  Dense,Flatten,MaxPool1D,Activation,Dropout,MaxPooling1D
from tensorflow.keras.layers import Conv1D,Dropout,GlobalMaxPooling1D,Embedding

In [24]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from numpy import array

In [25]:
df=pd.read_csv('/content/twitter4000.csv')

In [26]:
df.head()

twitts  sentiment
0  is bored and wants to watch a movie  any sugge...          0
1           back in miami.  waiting to unboard ship           0
2  @misskpey awwww dnt dis brng bak memoriessss, ...          0
3                  ughhh i am so tired  blahhhhhhhhh          0
4  @mandagoforth me bad! It's funny though. Zacha...          0

In [27]:
df.sentiment.value_counts()

1    2000
0    2000
Name: sentiment, dtype: int64

In [28]:
tweet_list=df.twitts.to_list()

In [29]:
tweet_list[:5]

['is bored and wants to watch a movie  any suggestions?',
 'back in miami.  waiting to unboard ship ',
 "@misskpey awwww dnt dis brng bak memoriessss,  I thnk I'm sad. LoL",
 'ughhh i am so tired  blahhhhhhhhh',
 "@mandagoforth me bad! It's funny though. Zachary Quinto is only there for a few though.  &amp; to reply just put the @ symbol before the name!"]

In [30]:
y=df.sentiment
token=Tokenizer()


In [31]:
token.fit_on_texts(tweet_list)

In [32]:
token.word_index

{'i': 1,
 'to': 2,
 'the': 3,
 'a': 4,
 'my': 5,
 'and': 6,
 'you': 7,
 'is': 8,
 'it': 9,
 'in': 10,
 'for': 11,
 'of': 12,
 'me': 13,
 'on': 14,
 'so': 15,
 'that': 16,
 "i'm": 17,
 'have': 18,
 'at': 19,
 'but': 20,
 'just': 21,
 'was': 22,
 'with': 23,
 'not': 24,
 'be': 25,
 'this': 26,
 'day': 27,
 'up': 28,
 'now': 29,
 'good': 30,
 'all': 31,
 'get': 32,
 'out': 33,
 'go': 34,
 'no': 35,
 'http': 36,
 'today': 37,
 'like': 38,
 'are': 39,
 'love': 40,
 'your': 41,
 'quot': 42,
 'too': 43,
 'lol': 44,
 'work': 45,
 'got': 46,
 "it's": 47,
 'amp': 48,
 'do': 49,
 'com': 50,
 'u': 51,
 'back': 52,
 'going': 53,
 'what': 54,
 'time': 55,
 'from': 56,
 'had': 57,
 'will': 58,
 'know': 59,
 'about': 60,
 'im': 61,
 'am': 62,
 "don't": 63,
 'can': 64,
 'one': 65,
 'really': 66,
 "can't": 67,
 'we': 68,
 'oh': 69,
 'well': 70,
 'still': 71,
 '2': 72,
 'some': 73,
 'its': 74,
 'miss': 75,
 'want': 76,
 'see': 77,
 'when': 78,
 'home': 79,
 'think': 80,
 'an': 81,
 'as': 82,
 'if': 83,
 

In [33]:
vocab_size=len(token.word_index)+1

In [34]:
import itertools 
print(dict(itertools.islice(token.index_word.items(), 100)))

{1: 'i', 2: 'to', 3: 'the', 4: 'a', 5: 'my', 6: 'and', 7: 'you', 8: 'is', 9: 'it', 10: 'in', 11: 'for', 12: 'of', 13: 'me', 14: 'on', 15: 'so', 16: 'that', 17: "i'm", 18: 'have', 19: 'at', 20: 'but', 21: 'just', 22: 'was', 23: 'with', 24: 'not', 25: 'be', 26: 'this', 27: 'day', 28: 'up', 29: 'now', 30: 'good', 31: 'all', 32: 'get', 33: 'out', 34: 'go', 35: 'no', 36: 'http', 37: 'today', 38: 'like', 39: 'are', 40: 'love', 41: 'your', 42: 'quot', 43: 'too', 44: 'lol', 45: 'work', 46: 'got', 47: "it's", 48: 'amp', 49: 'do', 50: 'com', 51: 'u', 52: 'back', 53: 'going', 54: 'what', 55: 'time', 56: 'from', 57: 'had', 58: 'will', 59: 'know', 60: 'about', 61: 'im', 62: 'am', 63: "don't", 64: 'can', 65: 'one', 66: 'really', 67: "can't", 68: 'we', 69: 'oh', 70: 'well', 71: 'still', 72: '2', 73: 'some', 74: 'its', 75: 'miss', 76: 'want', 77: 'see', 78: 'when', 79: 'home', 80: 'think', 81: 'an', 82: 'as', 83: 'if', 84: 'night', 85: 'need', 86: 'again', 87: 'new', 88: 'there', 89: 'morning', 90: 'h

In [35]:
token.index_word.items()

dict_items([(1, 'i'), (2, 'to'), (3, 'the'), (4, 'a'), (5, 'my'), (6, 'and'), (7, 'you'), (8, 'is'), (9, 'it'), (10, 'in'), (11, 'for'), (12, 'of'), (13, 'me'), (14, 'on'), (15, 'so'), (16, 'that'), (17, "i'm"), (18, 'have'), (19, 'at'), (20, 'but'), (21, 'just'), (22, 'was'), (23, 'with'), (24, 'not'), (25, 'be'), (26, 'this'), (27, 'day'), (28, 'up'), (29, 'now'), (30, 'good'), (31, 'all'), (32, 'get'), (33, 'out'), (34, 'go'), (35, 'no'), (36, 'http'), (37, 'today'), (38, 'like'), (39, 'are'), (40, 'love'), (41, 'your'), (42, 'quot'), (43, 'too'), (44, 'lol'), (45, 'work'), (46, 'got'), (47, "it's"), (48, 'amp'), (49, 'do'), (50, 'com'), (51, 'u'), (52, 'back'), (53, 'going'), (54, 'what'), (55, 'time'), (56, 'from'), (57, 'had'), (58, 'will'), (59, 'know'), (60, 'about'), (61, 'im'), (62, 'am'), (63, "don't"), (64, 'can'), (65, 'one'), (66, 'really'), (67, "can't"), (68, 'we'), (69, 'oh'), (70, 'well'), (71, 'still'), (72, '2'), (73, 'some'), (74, 'its'), (75, 'miss'), (76, 'want')

In [36]:
dict(token.index_word.items())

{1: 'i',
 2: 'to',
 3: 'the',
 4: 'a',
 5: 'my',
 6: 'and',
 7: 'you',
 8: 'is',
 9: 'it',
 10: 'in',
 11: 'for',
 12: 'of',
 13: 'me',
 14: 'on',
 15: 'so',
 16: 'that',
 17: "i'm",
 18: 'have',
 19: 'at',
 20: 'but',
 21: 'just',
 22: 'was',
 23: 'with',
 24: 'not',
 25: 'be',
 26: 'this',
 27: 'day',
 28: 'up',
 29: 'now',
 30: 'good',
 31: 'all',
 32: 'get',
 33: 'out',
 34: 'go',
 35: 'no',
 36: 'http',
 37: 'today',
 38: 'like',
 39: 'are',
 40: 'love',
 41: 'your',
 42: 'quot',
 43: 'too',
 44: 'lol',
 45: 'work',
 46: 'got',
 47: "it's",
 48: 'amp',
 49: 'do',
 50: 'com',
 51: 'u',
 52: 'back',
 53: 'going',
 54: 'what',
 55: 'time',
 56: 'from',
 57: 'had',
 58: 'will',
 59: 'know',
 60: 'about',
 61: 'im',
 62: 'am',
 63: "don't",
 64: 'can',
 65: 'one',
 66: 'really',
 67: "can't",
 68: 'we',
 69: 'oh',
 70: 'well',
 71: 'still',
 72: '2',
 73: 'some',
 74: 'its',
 75: 'miss',
 76: 'want',
 77: 'see',
 78: 'when',
 79: 'home',
 80: 'think',
 81: 'an',
 82: 'as',
 83: 'if',
 

In [37]:
x = ['i to the a and']
token.texts_to_sequences(x)

[[1, 2, 3, 4, 6]]

In [38]:
encoded_text=token.texts_to_sequences(tweet_list)

In [39]:
encoded_text[:2]

[[8, 304, 6, 345, 2, 191, 4, 236, 254, 3079],
 [52, 10, 1019, 206, 2, 3080, 3081]]

In [40]:
max_length = 120
x = pad_sequences(encoded_text, maxlen=max_length, padding='post')
print(x)

[[    8   304     6 ...     0     0     0]
 [   52    10  1019 ...     0     0     0]
 [ 3082  1197   668 ...     0     0     0]
 ...
 [ 1033    21  1021 ...     0     0     0]
 [10134   134     7 ...     0     0     0]
 [   94    11   226 ...     0     0     0]]


In [41]:
len(x[0])

120

In [42]:
x.shape

(4000, 120)

In [43]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=77,stratify=y)

In [44]:
vec_size = 300

model = Sequential()
model.add(Embedding(vocab_size, vec_size, input_length=max_length))

In [45]:

model.add(Conv1D(64, 8, activation = 'relu'))
model.add(MaxPooling1D(2))
model.add(Dropout(0.2))

model.add(Dense(32, activation='relu'))
model.add(Dropout(0.5))

model.add(Dense(16, activation='relu'))

model.add(GlobalMaxPooling1D())

model.add(Dense(1, activation='sigmoid'))

In [46]:
model.compile(optimizer='adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [47]:

history=model.fit(x_train, y_train, epochs = 5, validation_data = (x_test, y_test))

Epoch 1/5
100/100 [==============================] - 13s 129ms/step - loss: 0.6906 - accuracy: 0.5234 - val_loss: 0.6884 - val_accuracy: 0.5200
Epoch 2/5
100/100 [==============================] - 13s 129ms/step - loss: 0.6240 - accuracy: 0.6616 - val_loss: 0.6215 - val_accuracy: 0.6687
Epoch 3/5
100/100 [==============================] - 13s 130ms/step - loss: 0.4293 - accuracy: 0.8219 - val_loss: 0.6189 - val_accuracy: 0.7038
Epoch 4/5
100/100 [==============================] - 13s 133ms/step - loss: 0.2404 - accuracy: 0.9122 - val_loss: 0.6459 - val_accuracy: 0.7100
Epoch 5/5
100/100 [==============================] - 13s 129ms/step - loss: 0.1052 - accuracy: 0.9628 - val_loss: 0.8134 - val_accuracy: 0.7125


In [48]:
def get_encoded(x):
    x = token.texts_to_sequences(x)
    x = pad_sequences(x, maxlen=max_length, padding = 'post')
    return x

x = ['worst services. will not come again']
model.predict_classes(get_encoded(x))

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


array([[0]], dtype=int32)